# SkinFetcher
# issues tracker: https://github.com/kacperduras/SkinFetcher/issues/

debug: false # debug configuration

queue:
  time: 2 # how many seconds the queue should refresh (min.: 1, recommended: 2-3)
