# SkinFetcher
# issues tracker: https://github.com/kacperduras/SkinFetcher/issues/

debug: false # debug configuration

queue:
  time: 2 # how many seconds the queue should refresh (min.: 1, recommended: 2-3)

messages:
  try-again: "&cToo many people are trying to connect at one time, wait and try again later."